debug: false
logging:
  level:
    com.sungmin.singletrain_borad: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/singletrain_board"
    username: "trainer"
    password: "artl0108!"